# Generated by Django 4.2.9 on 2024-07-13 20:16

import apps.tasks.choices.statuses
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.SmallIntegerField(choices=[(1, 'Very low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Critical')], default=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In progress'), ('PENDING', 'Pending'), ('BLOCKED', 'Blocked'), ('TESTING', 'Testing'), ('CLOSED', 'Closed')], default=apps.tasks.choices.statuses.Statuses['NEW'], max_length=15),
        ),
    ]
