# Generated by Django 4.2.9 on 2024-07-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('CEO', 'Ceo'), ('CTO', 'Cto'), ('DESIGNER', 'Designer'), ('PROGRAMMER', 'Programmer'), ('PRODUCT_OWNER', 'Product_owner'), ('PROJECT_OWNER', 'Project_owner'), ('PROJECT_MANAGER', 'Project_manager'), ('QA', 'QA')], max_length=20),
        ),
    ]
