name: Django Tests

on:
  push:
    branches: [ "the_last_hw" ]
  pull_request:
    branches: [ "the_last_hw" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [ "3.10" ]

    services:
          mysql:
            image: mysql:latest
            ports:
              - 3306:3306
            env:
              MYSQL_DATABASE: ${{ secrets.DB_NAME }}
              MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
              MYSQL_USER: ${{ secrets.DB_USER }}
              MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
            options: >-
              --health-cmd="mysqladmin ping --silent"
              --health-interval=10s
              --health-timeout=5s
              --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create .env file
        run: |
          echo 'SECRET_KEY=${{ secrets.SECRET_KEY }}' >> .env
          echo 'ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}' >> .env
          echo 'DB_HOST=${{ secrets.DB_HOST }}' >> .env
          echo 'DB_NAME=${{ secrets.DB_NAME }}' >> .env
          echo 'DB_PASSWORD=${{ secrets.DB_PASSWORD }}' >> .env
          echo 'DB_PORT=${{ secrets.DB_PORT }}' >> .env
          echo 'DB_USER=${{ secrets.DB_USER }}' >> .env
          echo 'DEBUG=${{ secrets.DEBUG }}' >> .env
          echo 'MYSQL=${{ secrets.MYSQL }}' >> .env

      - name: Wait for MySql
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if mysqladmin ping -h"${{ secrets.DB_HOST }}" -u"${{ secrets.DB_USER }}" -p'${{ secrets.DB_PASSWORD }}' --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL... ($i/30)"
            sleep 10
          done
          mysqladmin ping -h"${{ secrets.DB_HOST }}" -u"${{ secrets.DB_USER }}" -p'${{ secrets.DB_PASSWORD }}' --verbose

      - name: Make setup.sh executable and run it
        run: |
          chmod +x setup.sh
          ./setup.sh